// This file is part of zig-spoon, a TUI library for the zig language.
//
// Copyright © 2022 Hugo Machet
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 3 as published
// by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

const std = @import("std");
const ascii = std.ascii;
const fmt = std.fmt;
const mem = std.mem;

const Colour = @import("Attribute.zig").Colour;

/// A parser to convert an UTF8 string to an Attribute.Colour union.
/// RGB colours: "0xRRGGBB"
/// 256 colours: "154"
/// ANSI colours: A string equal to one of Colour fields (case sensitive)
///
/// Examples:
///     var rgb = try parseColourDescription("0x2b45a7");
///         -> Attribute{ .rgb = { 43, 69, 167 } };
///     var 256 = try parseColourDescription("234");
///         -> Attribute{ .@"256" = 234 };
///     var ansi = try parseColourDescription("red");
///         -> Attribute{ .red };
pub fn parseColourDescription(s: []const u8) !Colour {
    if (s.len == 0) return error.BadColourDescription;

    if (ascii.isDigit(s[0])) {
        if (s.len == "0xRRGGBB".len and s[0] == '0' and s[1] == 'x') {
            return Colour{ .rgb = try hexToRgb(s[2..]) };
        } else {
            return Colour{
                .@"256" = fmt.parseUnsigned(u8, s, 10) catch return error.BadColourDescription,
            };
        }
    } else {
        return colour_names.get(s) orelse error.BadColourDescription;
    }
}

/// Convert a string in the format "0xRRGGBB" to [3]u8.
fn hexToRgb(s: []const u8) ![3]u8 {
    if (s.len != 6) return error.BadRgbFormat;
    const r = fmt.parseUnsigned(u8, s[0..2], 16) catch return error.BadRgbFormat;
    const g = fmt.parseUnsigned(u8, s[2..4], 16) catch return error.BadRgbFormat;
    const b = fmt.parseUnsigned(u8, s[4..], 16) catch return error.BadRgbFormat;
    return [3]u8{ r, g, b };
}

test "parse colours string (good input)" {
    const testing = std.testing;
    try testing.expectEqual(
        Colour{ .rgb = .{ 255, 255, 255 } },
        try parseColourDescription("0xffffff"),
    );
    try testing.expectEqual(
        Colour{ .rgb = .{ 0, 0, 0 } },
        try parseColourDescription("0x000000"),
    );
    try testing.expectEqual(
        Colour{ .rgb = .{ 0, 169, 143 } },
        try parseColourDescription("0x00a98f"),
    );
    try testing.expectEqual(
        Colour{ .@"256" = 0 },
        try parseColourDescription("0"),
    );
    try testing.expectEqual(
        Colour{ .@"256" = 7 },
        try parseColourDescription("007"),
    );
    try testing.expectEqual(
        Colour{ .@"256" = 7 },
        try parseColourDescription("0000000000000000007"),
    );
    try testing.expectEqual(
        Colour{ .@"256" = 237 },
        try parseColourDescription("237"),
    );
    try testing.expectEqual(
        Colour.bright_black,
        try parseColourDescription("bright_black"),
    );
    try testing.expectEqual(
        Colour.blue,
        try parseColourDescription("blue"),
    );
}

test "parse colours string (bad input)" {
    const testing = std.testing;
    try testing.expectError(error.BadRgbFormat, parseColourDescription("0xppttjj"));
    try testing.expectError(error.BadColourDescription, parseColourDescription("0xfff"));
    try testing.expectError(error.BadColourDescription, parseColourDescription("0x"));
    try testing.expectError(error.BadColourDescription, parseColourDescription("0Xffffff"));
    try testing.expectError(error.BadColourDescription, parseColourDescription(""));
    try testing.expectError(error.BadColourDescription, parseColourDescription("xffffff"));
    try testing.expectError(error.BadColourDescription, parseColourDescription("ffffff"));
    try testing.expectError(error.BadColourDescription, parseColourDescription("blu"));
    try testing.expectError(error.BadColourDescription, parseColourDescription("bLue"));
    try testing.expectError(error.BadColourDescription, parseColourDescription("256"));
}

const colour_names = blk: {
    @setEvalBranchQuota(100000);
    break :blk std.ComptimeStringMap(Colour, .{
        // Terminal colours.
        .{ "none", .none },
        .{ "black", .black },
        .{ "red", .red },
        .{ "green", .green },
        .{ "yellow", .yellow },
        .{ "blue", .blue },
        .{ "magenta", .magenta },
        .{ "cyan", .cyan },
        .{ "white", .white },
        .{ "bright_black", .bright_black },
        .{ "bright_red", .bright_red },
        .{ "bright_green", .bright_green },
        .{ "bright_yellow", .bright_yellow },
        .{ "bright_blue", .bright_blue },
        .{ "bright_magenta", .bright_magenta },
        .{ "bright_cyan", .bright_cyan },
        .{ "bright_white", .bright_white },

        // HTML colours
        .{ "html:IndianRed", .{ .rgb = hexToRgb("CD5C5C") catch @compileError("Bad colour code.") } },
        .{ "html:LightCoral", .{ .rgb = hexToRgb("F08080") catch @compileError("Bad colour code.") } },
        .{ "html:Salmon", .{ .rgb = hexToRgb("FA8072") catch @compileError("Bad colour code.") } },
        .{ "html:DarkSalmon", .{ .rgb = hexToRgb("E9967A") catch @compileError("Bad colour code.") } },
        .{ "html:LightSalmon", .{ .rgb = hexToRgb("FFA07A") catch @compileError("Bad colour code.") } },
        .{ "html:Crimson", .{ .rgb = hexToRgb("DC143C") catch @compileError("Bad colour code.") } },
        .{ "html:Red", .{ .rgb = hexToRgb("FF0000") catch @compileError("Bad colour code.") } },
        .{ "html:FireBrick", .{ .rgb = hexToRgb("B22222") catch @compileError("Bad colour code.") } },
        .{ "html:DarkRed", .{ .rgb = hexToRgb("8B0000") catch @compileError("Bad colour code.") } },
        .{ "html:Pink", .{ .rgb = hexToRgb("FFC0CB") catch @compileError("Bad colour code.") } },
        .{ "html:LightPink", .{ .rgb = hexToRgb("FFB6C1") catch @compileError("Bad colour code.") } },
        .{ "html:HotPink", .{ .rgb = hexToRgb("FF69B4") catch @compileError("Bad colour code.") } },
        .{ "html:DeepPink", .{ .rgb = hexToRgb("FF1493") catch @compileError("Bad colour code.") } },
        .{ "html:MediumVioletRed", .{ .rgb = hexToRgb("C71585") catch @compileError("Bad colour code.") } },
        .{ "html:PaleVioletRed", .{ .rgb = hexToRgb("DB7093") catch @compileError("Bad colour code.") } },
        .{ "html:LightSalmon", .{ .rgb = hexToRgb("FFA07A") catch @compileError("Bad colour code.") } },
        .{ "html:Coral", .{ .rgb = hexToRgb("FF7F50") catch @compileError("Bad colour code.") } },
        .{ "html:Tomato", .{ .rgb = hexToRgb("FF6347") catch @compileError("Bad colour code.") } },
        .{ "html:OrangeRed", .{ .rgb = hexToRgb("FF4500") catch @compileError("Bad colour code.") } },
        .{ "html:DarkOrange", .{ .rgb = hexToRgb("FF8C00") catch @compileError("Bad colour code.") } },
        .{ "html:Orange", .{ .rgb = hexToRgb("FFA500") catch @compileError("Bad colour code.") } },
        .{ "html:Gold", .{ .rgb = hexToRgb("FFD700") catch @compileError("Bad colour code.") } },
        .{ "html:Yellow", .{ .rgb = hexToRgb("FFFF00") catch @compileError("Bad colour code.") } },
        .{ "html:LightYellow", .{ .rgb = hexToRgb("FFFFE0") catch @compileError("Bad colour code.") } },
        .{ "html:LemonChiffon", .{ .rgb = hexToRgb("FFFACD") catch @compileError("Bad colour code.") } },
        .{ "html:LightGoldenrodYellow", .{ .rgb = hexToRgb("FAFAD2") catch @compileError("Bad colour code.") } },
        .{ "html:PapayaWhip", .{ .rgb = hexToRgb("FFEFD5") catch @compileError("Bad colour code.") } },
        .{ "html:Moccasin", .{ .rgb = hexToRgb("FFE4B5") catch @compileError("Bad colour code.") } },
        .{ "html:PeachPuff", .{ .rgb = hexToRgb("FFDAB9") catch @compileError("Bad colour code.") } },
        .{ "html:PaleGoldenrod", .{ .rgb = hexToRgb("EEE8AA") catch @compileError("Bad colour code.") } },
        .{ "html:Khaki", .{ .rgb = hexToRgb("F0E68C") catch @compileError("Bad colour code.") } },
        .{ "html:DarkKhaki", .{ .rgb = hexToRgb("BDB76B") catch @compileError("Bad colour code.") } },
        .{ "html:Lavender", .{ .rgb = hexToRgb("E6E6FA") catch @compileError("Bad colour code.") } },
        .{ "html:Thistle", .{ .rgb = hexToRgb("D8BFD8") catch @compileError("Bad colour code.") } },
        .{ "html:Plum", .{ .rgb = hexToRgb("DDA0DD") catch @compileError("Bad colour code.") } },
        .{ "html:Violet", .{ .rgb = hexToRgb("EE82EE") catch @compileError("Bad colour code.") } },
        .{ "html:Orchid", .{ .rgb = hexToRgb("DA70D6") catch @compileError("Bad colour code.") } },
        .{ "html:Fuchsia", .{ .rgb = hexToRgb("FF00FF") catch @compileError("Bad colour code.") } },
        .{ "html:Magenta", .{ .rgb = hexToRgb("FF00FF") catch @compileError("Bad colour code.") } },
        .{ "html:MediumOrchid", .{ .rgb = hexToRgb("BA55D3") catch @compileError("Bad colour code.") } },
        .{ "html:MediumPurple", .{ .rgb = hexToRgb("9370DB") catch @compileError("Bad colour code.") } },
        .{ "html:Amethyst", .{ .rgb = hexToRgb("9966CC") catch @compileError("Bad colour code.") } },
        .{ "html:BlueViolet", .{ .rgb = hexToRgb("8A2BE2") catch @compileError("Bad colour code.") } },
        .{ "html:DarkViolet", .{ .rgb = hexToRgb("9400D3") catch @compileError("Bad colour code.") } },
        .{ "html:DarkOrchid", .{ .rgb = hexToRgb("9932CC") catch @compileError("Bad colour code.") } },
        .{ "html:DarkMagenta", .{ .rgb = hexToRgb("8B008B") catch @compileError("Bad colour code.") } },
        .{ "html:Purple", .{ .rgb = hexToRgb("800080") catch @compileError("Bad colour code.") } },
        .{ "html:Indigo", .{ .rgb = hexToRgb("4B0082") catch @compileError("Bad colour code.") } },
        .{ "html:SlateBlue", .{ .rgb = hexToRgb("6A5ACD") catch @compileError("Bad colour code.") } },
        .{ "html:DarkSlateBlue", .{ .rgb = hexToRgb("483D8B") catch @compileError("Bad colour code.") } },
        .{ "html:MediumSlateBlue", .{ .rgb = hexToRgb("7B68EE") catch @compileError("Bad colour code.") } },
        .{ "html:GreenYellow", .{ .rgb = hexToRgb("ADFF2F") catch @compileError("Bad colour code.") } },
        .{ "html:Chartreuse", .{ .rgb = hexToRgb("7FFF00") catch @compileError("Bad colour code.") } },
        .{ "html:LawnGreen", .{ .rgb = hexToRgb("7CFC00") catch @compileError("Bad colour code.") } },
        .{ "html:Lime", .{ .rgb = hexToRgb("00FF00") catch @compileError("Bad colour code.") } },
        .{ "html:LimeGreen", .{ .rgb = hexToRgb("32CD32") catch @compileError("Bad colour code.") } },
        .{ "html:PaleGreen", .{ .rgb = hexToRgb("98FB98") catch @compileError("Bad colour code.") } },
        .{ "html:LightGreen", .{ .rgb = hexToRgb("90EE90") catch @compileError("Bad colour code.") } },
        .{ "html:MediumSpringGreen", .{ .rgb = hexToRgb("00FA9A") catch @compileError("Bad colour code.") } },
        .{ "html:SpringGreen", .{ .rgb = hexToRgb("00FF7F") catch @compileError("Bad colour code.") } },
        .{ "html:MediumSeaGreen", .{ .rgb = hexToRgb("3CB371") catch @compileError("Bad colour code.") } },
        .{ "html:SeaGreen", .{ .rgb = hexToRgb("2E8B57") catch @compileError("Bad colour code.") } },
        .{ "html:ForestGreen", .{ .rgb = hexToRgb("228B22") catch @compileError("Bad colour code.") } },
        .{ "html:Green", .{ .rgb = hexToRgb("008000") catch @compileError("Bad colour code.") } },
        .{ "html:DarkGreen", .{ .rgb = hexToRgb("006400") catch @compileError("Bad colour code.") } },
        .{ "html:YellowGreen", .{ .rgb = hexToRgb("9ACD32") catch @compileError("Bad colour code.") } },
        .{ "html:OliveDrab", .{ .rgb = hexToRgb("6B8E23") catch @compileError("Bad colour code.") } },
        .{ "html:Olive", .{ .rgb = hexToRgb("808000") catch @compileError("Bad colour code.") } },
        .{ "html:DarkOliveGreen", .{ .rgb = hexToRgb("556B2F") catch @compileError("Bad colour code.") } },
        .{ "html:MediumAquamarine", .{ .rgb = hexToRgb("66CDAA") catch @compileError("Bad colour code.") } },
        .{ "html:DarkSeaGreen", .{ .rgb = hexToRgb("8FBC8F") catch @compileError("Bad colour code.") } },
        .{ "html:LightSeaGreen", .{ .rgb = hexToRgb("20B2AA") catch @compileError("Bad colour code.") } },
        .{ "html:DarkCyan", .{ .rgb = hexToRgb("008B8B") catch @compileError("Bad colour code.") } },
        .{ "html:Teal", .{ .rgb = hexToRgb("008080") catch @compileError("Bad colour code.") } },
        .{ "html:Aqua", .{ .rgb = hexToRgb("00FFFF") catch @compileError("Bad colour code.") } },
        .{ "html:Cyan", .{ .rgb = hexToRgb("00FFFF") catch @compileError("Bad colour code.") } },
        .{ "html:LightCyan", .{ .rgb = hexToRgb("E0FFFF") catch @compileError("Bad colour code.") } },
        .{ "html:PaleTurquoise", .{ .rgb = hexToRgb("AFEEEE") catch @compileError("Bad colour code.") } },
        .{ "html:Aquamarine", .{ .rgb = hexToRgb("7FFFD4") catch @compileError("Bad colour code.") } },
        .{ "html:Turquoise", .{ .rgb = hexToRgb("40E0D0") catch @compileError("Bad colour code.") } },
        .{ "html:MediumTurquoise", .{ .rgb = hexToRgb("48D1CC") catch @compileError("Bad colour code.") } },
        .{ "html:DarkTurquoise", .{ .rgb = hexToRgb("00CED1") catch @compileError("Bad colour code.") } },
        .{ "html:CadetBlue", .{ .rgb = hexToRgb("5F9EA0") catch @compileError("Bad colour code.") } },
        .{ "html:SteelBlue", .{ .rgb = hexToRgb("4682B4") catch @compileError("Bad colour code.") } },
        .{ "html:LightSteelBlue", .{ .rgb = hexToRgb("B0C4DE") catch @compileError("Bad colour code.") } },
        .{ "html:PowderBlue", .{ .rgb = hexToRgb("B0E0E6") catch @compileError("Bad colour code.") } },
        .{ "html:LightBlue", .{ .rgb = hexToRgb("ADD8E6") catch @compileError("Bad colour code.") } },
        .{ "html:SkyBlue", .{ .rgb = hexToRgb("87CEEB") catch @compileError("Bad colour code.") } },
        .{ "html:LightSkyBlue", .{ .rgb = hexToRgb("87CEFA") catch @compileError("Bad colour code.") } },
        .{ "html:DeepSkyBlue", .{ .rgb = hexToRgb("00BFFF") catch @compileError("Bad colour code.") } },
        .{ "html:DodgerBlue", .{ .rgb = hexToRgb("1E90FF") catch @compileError("Bad colour code.") } },
        .{ "html:CornflowerBlue", .{ .rgb = hexToRgb("6495ED") catch @compileError("Bad colour code.") } },
        .{ "html:MediumSlateBlue", .{ .rgb = hexToRgb("7B68EE") catch @compileError("Bad colour code.") } },
        .{ "html:RoyalBlue", .{ .rgb = hexToRgb("4169E1") catch @compileError("Bad colour code.") } },
        .{ "html:Blue", .{ .rgb = hexToRgb("0000FF") catch @compileError("Bad colour code.") } },
        .{ "html:MediumBlue", .{ .rgb = hexToRgb("0000CD") catch @compileError("Bad colour code.") } },
        .{ "html:DarkBlue", .{ .rgb = hexToRgb("00008B") catch @compileError("Bad colour code.") } },
        .{ "html:Navy", .{ .rgb = hexToRgb("000080") catch @compileError("Bad colour code.") } },
        .{ "html:MidnightBlue", .{ .rgb = hexToRgb("191970") catch @compileError("Bad colour code.") } },
        .{ "html:Cornsilk", .{ .rgb = hexToRgb("FFF8DC") catch @compileError("Bad colour code.") } },
        .{ "html:BlanchedAlmond", .{ .rgb = hexToRgb("FFEBCD") catch @compileError("Bad colour code.") } },
        .{ "html:Bisque", .{ .rgb = hexToRgb("FFE4C4") catch @compileError("Bad colour code.") } },
        .{ "html:NavajoWhite", .{ .rgb = hexToRgb("FFDEAD") catch @compileError("Bad colour code.") } },
        .{ "html:Wheat", .{ .rgb = hexToRgb("F5DEB3") catch @compileError("Bad colour code.") } },
        .{ "html:BurlyWood", .{ .rgb = hexToRgb("DEB887") catch @compileError("Bad colour code.") } },
        .{ "html:Tan", .{ .rgb = hexToRgb("D2B48C") catch @compileError("Bad colour code.") } },
        .{ "html:RosyBrown", .{ .rgb = hexToRgb("BC8F8F") catch @compileError("Bad colour code.") } },
        .{ "html:SandyBrown", .{ .rgb = hexToRgb("F4A460") catch @compileError("Bad colour code.") } },
        .{ "html:Goldenrod", .{ .rgb = hexToRgb("DAA520") catch @compileError("Bad colour code.") } },
        .{ "html:DarkGoldenrod", .{ .rgb = hexToRgb("B8860B") catch @compileError("Bad colour code.") } },
        .{ "html:Peru", .{ .rgb = hexToRgb("CD853F") catch @compileError("Bad colour code.") } },
        .{ "html:Chocolate", .{ .rgb = hexToRgb("D2691E") catch @compileError("Bad colour code.") } },
        .{ "html:SaddleBrown", .{ .rgb = hexToRgb("8B4513") catch @compileError("Bad colour code.") } },
        .{ "html:Sienna", .{ .rgb = hexToRgb("A0522D") catch @compileError("Bad colour code.") } },
        .{ "html:Brown", .{ .rgb = hexToRgb("A52A2A") catch @compileError("Bad colour code.") } },
        .{ "html:Maroon", .{ .rgb = hexToRgb("800000") catch @compileError("Bad colour code.") } },
        .{ "html:White", .{ .rgb = hexToRgb("FFFFFF") catch @compileError("Bad colour code.") } },
        .{ "html:Snow", .{ .rgb = hexToRgb("FFFAFA") catch @compileError("Bad colour code.") } },
        .{ "html:Honeydew", .{ .rgb = hexToRgb("F0FFF0") catch @compileError("Bad colour code.") } },
        .{ "html:MintCream", .{ .rgb = hexToRgb("F5FFFA") catch @compileError("Bad colour code.") } },
        .{ "html:Azure", .{ .rgb = hexToRgb("F0FFFF") catch @compileError("Bad colour code.") } },
        .{ "html:AliceBlue", .{ .rgb = hexToRgb("F0F8FF") catch @compileError("Bad colour code.") } },
        .{ "html:GhostWhite", .{ .rgb = hexToRgb("F8F8FF") catch @compileError("Bad colour code.") } },
        .{ "html:WhiteSmoke", .{ .rgb = hexToRgb("F5F5F5") catch @compileError("Bad colour code.") } },
        .{ "html:Seashell", .{ .rgb = hexToRgb("FFF5EE") catch @compileError("Bad colour code.") } },
        .{ "html:Beige", .{ .rgb = hexToRgb("F5F5DC") catch @compileError("Bad colour code.") } },
        .{ "html:OldLace", .{ .rgb = hexToRgb("FDF5E6") catch @compileError("Bad colour code.") } },
        .{ "html:FloralWhite", .{ .rgb = hexToRgb("FFFAF0") catch @compileError("Bad colour code.") } },
        .{ "html:Ivory", .{ .rgb = hexToRgb("FFFFF0") catch @compileError("Bad colour code.") } },
        .{ "html:AntiqueWhite", .{ .rgb = hexToRgb("FAEBD7") catch @compileError("Bad colour code.") } },
        .{ "html:Linen", .{ .rgb = hexToRgb("FAF0E6") catch @compileError("Bad colour code.") } },
        .{ "html:LavenderBlush", .{ .rgb = hexToRgb("FFF0F5") catch @compileError("Bad colour code.") } },
        .{ "html:MistyRose", .{ .rgb = hexToRgb("FFE4E1") catch @compileError("Bad colour code.") } },
        .{ "html:Gainsboro", .{ .rgb = hexToRgb("DCDCDC") catch @compileError("Bad colour code.") } },
        .{ "html:LightGrey", .{ .rgb = hexToRgb("D3D3D3") catch @compileError("Bad colour code.") } },
        .{ "html:Silver", .{ .rgb = hexToRgb("C0C0C0") catch @compileError("Bad colour code.") } },
        .{ "html:DarkGray", .{ .rgb = hexToRgb("A9A9A9") catch @compileError("Bad colour code.") } },
        .{ "html:Gray", .{ .rgb = hexToRgb("808080") catch @compileError("Bad colour code.") } },
        .{ "html:DimGray", .{ .rgb = hexToRgb("696969") catch @compileError("Bad colour code.") } },
        .{ "html:LightSlateGray", .{ .rgb = hexToRgb("778899") catch @compileError("Bad colour code.") } },
        .{ "html:SlateGray", .{ .rgb = hexToRgb("708090") catch @compileError("Bad colour code.") } },
        .{ "html:DarkSlateGray", .{ .rgb = hexToRgb("2F4F4F") catch @compileError("Bad colour code.") } },
        .{ "html:Black", .{ .rgb = hexToRgb("000000") catch @compileError("Bad colour code.") } },

        // X11 colour codes.
        .{ "x11:aliceblue", .{ .rgb = hexToRgb("f0f8ff") catch @compileError("Bad colour code.") } },
        .{ "x11:antiquewhite", .{ .rgb = hexToRgb("faebd7") catch @compileError("Bad colour code.") } },
        .{ "x11:antiquewhite1", .{ .rgb = hexToRgb("ffefdb") catch @compileError("Bad colour code.") } },
        .{ "x11:antiquewhite2", .{ .rgb = hexToRgb("eedfcc") catch @compileError("Bad colour code.") } },
        .{ "x11:antiquewhite3", .{ .rgb = hexToRgb("cdc0b0") catch @compileError("Bad colour code.") } },
        .{ "x11:antiquewhite4", .{ .rgb = hexToRgb("8b8378") catch @compileError("Bad colour code.") } },
        .{ "x11:aquamarine1", .{ .rgb = hexToRgb("7fffd4") catch @compileError("Bad colour code.") } },
        .{ "x11:aquamarine2", .{ .rgb = hexToRgb("76eec6") catch @compileError("Bad colour code.") } },
        .{ "x11:aquamarine4", .{ .rgb = hexToRgb("458b74") catch @compileError("Bad colour code.") } },
        .{ "x11:azure1", .{ .rgb = hexToRgb("f0ffff") catch @compileError("Bad colour code.") } },
        .{ "x11:azure2", .{ .rgb = hexToRgb("e0eeee") catch @compileError("Bad colour code.") } },
        .{ "x11:azure3", .{ .rgb = hexToRgb("c1cdcd") catch @compileError("Bad colour code.") } },
        .{ "x11:azure4", .{ .rgb = hexToRgb("838b8b") catch @compileError("Bad colour code.") } },
        .{ "x11:beige", .{ .rgb = hexToRgb("f5f5dc") catch @compileError("Bad colour code.") } },
        .{ "x11:bisque1", .{ .rgb = hexToRgb("ffe4c4") catch @compileError("Bad colour code.") } },
        .{ "x11:bisque2", .{ .rgb = hexToRgb("eed5b7") catch @compileError("Bad colour code.") } },
        .{ "x11:bisque3", .{ .rgb = hexToRgb("cdb79e") catch @compileError("Bad colour code.") } },
        .{ "x11:bisque4", .{ .rgb = hexToRgb("8b7d6b") catch @compileError("Bad colour code.") } },
        .{ "x11:black", .{ .rgb = hexToRgb("000000") catch @compileError("Bad colour code.") } },
        .{ "x11:blanchedalmond", .{ .rgb = hexToRgb("ffebcd") catch @compileError("Bad colour code.") } },
        .{ "x11:blue1", .{ .rgb = hexToRgb("0000ff") catch @compileError("Bad colour code.") } },
        .{ "x11:blue2", .{ .rgb = hexToRgb("0000ee") catch @compileError("Bad colour code.") } },
        .{ "x11:blue4", .{ .rgb = hexToRgb("00008b") catch @compileError("Bad colour code.") } },
        .{ "x11:blueviolet", .{ .rgb = hexToRgb("8a2be2") catch @compileError("Bad colour code.") } },
        .{ "x11:brown", .{ .rgb = hexToRgb("a52a2a") catch @compileError("Bad colour code.") } },
        .{ "x11:brown1", .{ .rgb = hexToRgb("ff4040") catch @compileError("Bad colour code.") } },
        .{ "x11:brown2", .{ .rgb = hexToRgb("ee3b3b") catch @compileError("Bad colour code.") } },
        .{ "x11:brown3", .{ .rgb = hexToRgb("cd3333") catch @compileError("Bad colour code.") } },
        .{ "x11:brown4", .{ .rgb = hexToRgb("8b2323") catch @compileError("Bad colour code.") } },
        .{ "x11:burlywood", .{ .rgb = hexToRgb("deb887") catch @compileError("Bad colour code.") } },
        .{ "x11:burlywood1", .{ .rgb = hexToRgb("ffd39b") catch @compileError("Bad colour code.") } },
        .{ "x11:burlywood2", .{ .rgb = hexToRgb("eec591") catch @compileError("Bad colour code.") } },
        .{ "x11:burlywood3", .{ .rgb = hexToRgb("cdaa7d") catch @compileError("Bad colour code.") } },
        .{ "x11:burlywood4", .{ .rgb = hexToRgb("8b7355") catch @compileError("Bad colour code.") } },
        .{ "x11:cadetblue", .{ .rgb = hexToRgb("5f9ea0") catch @compileError("Bad colour code.") } },
        .{ "x11:cadetblue1", .{ .rgb = hexToRgb("98f5ff") catch @compileError("Bad colour code.") } },
        .{ "x11:cadetblue2", .{ .rgb = hexToRgb("8ee5ee") catch @compileError("Bad colour code.") } },
        .{ "x11:cadetblue3", .{ .rgb = hexToRgb("7ac5cd") catch @compileError("Bad colour code.") } },
        .{ "x11:cadetblue4", .{ .rgb = hexToRgb("53868b") catch @compileError("Bad colour code.") } },
        .{ "x11:chartreuse1", .{ .rgb = hexToRgb("7fff00") catch @compileError("Bad colour code.") } },
        .{ "x11:chartreuse2", .{ .rgb = hexToRgb("76ee00") catch @compileError("Bad colour code.") } },
        .{ "x11:chartreuse3", .{ .rgb = hexToRgb("66cd00") catch @compileError("Bad colour code.") } },
        .{ "x11:chartreuse4", .{ .rgb = hexToRgb("458b00") catch @compileError("Bad colour code.") } },
        .{ "x11:chocolate", .{ .rgb = hexToRgb("d2691e") catch @compileError("Bad colour code.") } },
        .{ "x11:chocolate1", .{ .rgb = hexToRgb("ff7f24") catch @compileError("Bad colour code.") } },
        .{ "x11:chocolate2", .{ .rgb = hexToRgb("ee7621") catch @compileError("Bad colour code.") } },
        .{ "x11:chocolate3", .{ .rgb = hexToRgb("cd661d") catch @compileError("Bad colour code.") } },
        .{ "x11:coral", .{ .rgb = hexToRgb("ff7f50") catch @compileError("Bad colour code.") } },
        .{ "x11:coral1", .{ .rgb = hexToRgb("ff7256") catch @compileError("Bad colour code.") } },
        .{ "x11:coral2", .{ .rgb = hexToRgb("ee6a50") catch @compileError("Bad colour code.") } },
        .{ "x11:coral3", .{ .rgb = hexToRgb("cd5b45") catch @compileError("Bad colour code.") } },
        .{ "x11:coral4", .{ .rgb = hexToRgb("8b3e2f") catch @compileError("Bad colour code.") } },
        .{ "x11:cornflowerblue", .{ .rgb = hexToRgb("6495ed") catch @compileError("Bad colour code.") } },
        .{ "x11:cornsilk1", .{ .rgb = hexToRgb("fff8dc") catch @compileError("Bad colour code.") } },
        .{ "x11:cornsilk2", .{ .rgb = hexToRgb("eee8cd") catch @compileError("Bad colour code.") } },
        .{ "x11:cornsilk3", .{ .rgb = hexToRgb("cdc8b1") catch @compileError("Bad colour code.") } },
        .{ "x11:cornsilk4", .{ .rgb = hexToRgb("8b8878") catch @compileError("Bad colour code.") } },
        .{ "x11:cyan1", .{ .rgb = hexToRgb("00ffff") catch @compileError("Bad colour code.") } },
        .{ "x11:cyan2", .{ .rgb = hexToRgb("00eeee") catch @compileError("Bad colour code.") } },
        .{ "x11:cyan3", .{ .rgb = hexToRgb("00cdcd") catch @compileError("Bad colour code.") } },
        .{ "x11:cyan4", .{ .rgb = hexToRgb("008b8b") catch @compileError("Bad colour code.") } },
        .{ "x11:carkgoldenrod", .{ .rgb = hexToRgb("b8860b") catch @compileError("Bad colour code.") } },
        .{ "x11:carkgoldenrod1", .{ .rgb = hexToRgb("ffb90f") catch @compileError("Bad colour code.") } },
        .{ "x11:carkgoldenrod2", .{ .rgb = hexToRgb("eead0e") catch @compileError("Bad colour code.") } },
        .{ "x11:carkgoldenrod3", .{ .rgb = hexToRgb("cd950c") catch @compileError("Bad colour code.") } },
        .{ "x11:carkgoldenrod4", .{ .rgb = hexToRgb("8b6508") catch @compileError("Bad colour code.") } },
        .{ "x11:carkgreen", .{ .rgb = hexToRgb("006400") catch @compileError("Bad colour code.") } },
        .{ "x11:carkkhaki", .{ .rgb = hexToRgb("bdb76b") catch @compileError("Bad colour code.") } },
        .{ "x11:carkolivegreen", .{ .rgb = hexToRgb("556b2f") catch @compileError("Bad colour code.") } },
        .{ "x11:carkolivegreen1", .{ .rgb = hexToRgb("caff70") catch @compileError("Bad colour code.") } },
        .{ "x11:carkolivegreen2", .{ .rgb = hexToRgb("bcee68") catch @compileError("Bad colour code.") } },
        .{ "x11:carkolivegreen3", .{ .rgb = hexToRgb("a2cd5a") catch @compileError("Bad colour code.") } },
        .{ "x11:carkolivegreen4", .{ .rgb = hexToRgb("6e8b3d") catch @compileError("Bad colour code.") } },
        .{ "x11:carkorange", .{ .rgb = hexToRgb("ff8c00") catch @compileError("Bad colour code.") } },
        .{ "x11:carkorange1", .{ .rgb = hexToRgb("ff7f00") catch @compileError("Bad colour code.") } },
        .{ "x11:carkorange2", .{ .rgb = hexToRgb("ee7600") catch @compileError("Bad colour code.") } },
        .{ "x11:carkorange3", .{ .rgb = hexToRgb("cd6600") catch @compileError("Bad colour code.") } },
        .{ "x11:carkorange4", .{ .rgb = hexToRgb("8b4500") catch @compileError("Bad colour code.") } },
        .{ "x11:carkorchid", .{ .rgb = hexToRgb("9932cc") catch @compileError("Bad colour code.") } },
        .{ "x11:carkorchid1", .{ .rgb = hexToRgb("bf3eff") catch @compileError("Bad colour code.") } },
        .{ "x11:carkorchid2", .{ .rgb = hexToRgb("b23aee") catch @compileError("Bad colour code.") } },
        .{ "x11:carkorchid3", .{ .rgb = hexToRgb("9a32cd") catch @compileError("Bad colour code.") } },
        .{ "x11:carkorchid4", .{ .rgb = hexToRgb("68228b") catch @compileError("Bad colour code.") } },
        .{ "x11:carksalmon", .{ .rgb = hexToRgb("e9967a") catch @compileError("Bad colour code.") } },
        .{ "x11:carkseagreen", .{ .rgb = hexToRgb("8fbc8f") catch @compileError("Bad colour code.") } },
        .{ "x11:carkseagreen1", .{ .rgb = hexToRgb("c1ffc1") catch @compileError("Bad colour code.") } },
        .{ "x11:carkseagreen2", .{ .rgb = hexToRgb("b4eeb4") catch @compileError("Bad colour code.") } },
        .{ "x11:carkseagreen3", .{ .rgb = hexToRgb("9bcd9b") catch @compileError("Bad colour code.") } },
        .{ "x11:carkseagreen4", .{ .rgb = hexToRgb("698b69") catch @compileError("Bad colour code.") } },
        .{ "x11:carkslateblue", .{ .rgb = hexToRgb("483d8b") catch @compileError("Bad colour code.") } },
        .{ "x11:carkslategray", .{ .rgb = hexToRgb("2f4f4f") catch @compileError("Bad colour code.") } },
        .{ "x11:carkslategray1", .{ .rgb = hexToRgb("97ffff") catch @compileError("Bad colour code.") } },
        .{ "x11:carkslategray2", .{ .rgb = hexToRgb("8deeee") catch @compileError("Bad colour code.") } },
        .{ "x11:carkslategray3", .{ .rgb = hexToRgb("79cdcd") catch @compileError("Bad colour code.") } },
        .{ "x11:carkslategray4", .{ .rgb = hexToRgb("528b8b") catch @compileError("Bad colour code.") } },
        .{ "x11:carkturquoise", .{ .rgb = hexToRgb("00ced1") catch @compileError("Bad colour code.") } },
        .{ "x11:carkviolet", .{ .rgb = hexToRgb("9400d3") catch @compileError("Bad colour code.") } },
        .{ "x11:ceeppink1", .{ .rgb = hexToRgb("ff1493") catch @compileError("Bad colour code.") } },
        .{ "x11:ceeppink2", .{ .rgb = hexToRgb("ee1289") catch @compileError("Bad colour code.") } },
        .{ "x11:ceeppink3", .{ .rgb = hexToRgb("cd1076") catch @compileError("Bad colour code.") } },
        .{ "x11:ceeppink4", .{ .rgb = hexToRgb("8b0a50") catch @compileError("Bad colour code.") } },
        .{ "x11:ceepskyblue1", .{ .rgb = hexToRgb("00bfff") catch @compileError("Bad colour code.") } },
        .{ "x11:ceepskyblue2", .{ .rgb = hexToRgb("00b2ee") catch @compileError("Bad colour code.") } },
        .{ "x11:ceepskyblue3", .{ .rgb = hexToRgb("009acd") catch @compileError("Bad colour code.") } },
        .{ "x11:ceepskyblue4", .{ .rgb = hexToRgb("00688b") catch @compileError("Bad colour code.") } },
        .{ "x11:cimgray", .{ .rgb = hexToRgb("696969") catch @compileError("Bad colour code.") } },
        .{ "x11:codgerblue1", .{ .rgb = hexToRgb("1e90ff") catch @compileError("Bad colour code.") } },
        .{ "x11:codgerblue2", .{ .rgb = hexToRgb("1c86ee") catch @compileError("Bad colour code.") } },
        .{ "x11:codgerblue3", .{ .rgb = hexToRgb("1874cd") catch @compileError("Bad colour code.") } },
        .{ "x11:codgerblue4", .{ .rgb = hexToRgb("104e8b") catch @compileError("Bad colour code.") } },
        .{ "x11:cirebrick", .{ .rgb = hexToRgb("b22222") catch @compileError("Bad colour code.") } },
        .{ "x11:cirebrick1", .{ .rgb = hexToRgb("ff3030") catch @compileError("Bad colour code.") } },
        .{ "x11:cirebrick2", .{ .rgb = hexToRgb("ee2c2c") catch @compileError("Bad colour code.") } },
        .{ "x11:cirebrick3", .{ .rgb = hexToRgb("cd2626") catch @compileError("Bad colour code.") } },
        .{ "x11:cirebrick4", .{ .rgb = hexToRgb("8b1a1a") catch @compileError("Bad colour code.") } },
        .{ "x11:cloralwhite", .{ .rgb = hexToRgb("fffaf0") catch @compileError("Bad colour code.") } },
        .{ "x11:corestgreen", .{ .rgb = hexToRgb("228b22") catch @compileError("Bad colour code.") } },
        .{ "x11:cainsboro", .{ .rgb = hexToRgb("dcdcdc") catch @compileError("Bad colour code.") } },
        .{ "x11:chostwhite", .{ .rgb = hexToRgb("f8f8ff") catch @compileError("Bad colour code.") } },
        .{ "x11:cold1", .{ .rgb = hexToRgb("ffd700") catch @compileError("Bad colour code.") } },
        .{ "x11:cold2", .{ .rgb = hexToRgb("eec900") catch @compileError("Bad colour code.") } },
        .{ "x11:cold3", .{ .rgb = hexToRgb("cdad00") catch @compileError("Bad colour code.") } },
        .{ "x11:cold4", .{ .rgb = hexToRgb("8b7500") catch @compileError("Bad colour code.") } },
        .{ "x11:coldenrod", .{ .rgb = hexToRgb("daa520") catch @compileError("Bad colour code.") } },
        .{ "x11:coldenrod1", .{ .rgb = hexToRgb("ffc125") catch @compileError("Bad colour code.") } },
        .{ "x11:coldenrod2", .{ .rgb = hexToRgb("eeb422") catch @compileError("Bad colour code.") } },
        .{ "x11:coldenrod3", .{ .rgb = hexToRgb("cd9b1d") catch @compileError("Bad colour code.") } },
        .{ "x11:coldenrod4", .{ .rgb = hexToRgb("8b6914") catch @compileError("Bad colour code.") } },
        .{ "x11:cray", .{ .rgb = hexToRgb("bebebe") catch @compileError("Bad colour code.") } },
        .{ "x11:cray1", .{ .rgb = hexToRgb("030303") catch @compileError("Bad colour code.") } },
        .{ "x11:cray2", .{ .rgb = hexToRgb("050505") catch @compileError("Bad colour code.") } },
        .{ "x11:cray3", .{ .rgb = hexToRgb("080808") catch @compileError("Bad colour code.") } },
        .{ "x11:cray4", .{ .rgb = hexToRgb("0a0a0a") catch @compileError("Bad colour code.") } },
        .{ "x11:cray5", .{ .rgb = hexToRgb("0d0d0d") catch @compileError("Bad colour code.") } },
        .{ "x11:cray6", .{ .rgb = hexToRgb("0f0f0f") catch @compileError("Bad colour code.") } },
        .{ "x11:cray7", .{ .rgb = hexToRgb("121212") catch @compileError("Bad colour code.") } },
        .{ "x11:cray8", .{ .rgb = hexToRgb("141414") catch @compileError("Bad colour code.") } },
        .{ "x11:cray9", .{ .rgb = hexToRgb("171717") catch @compileError("Bad colour code.") } },
        .{ "x11:cray10", .{ .rgb = hexToRgb("1a1a1a") catch @compileError("Bad colour code.") } },
        .{ "x11:cray11", .{ .rgb = hexToRgb("1c1c1c") catch @compileError("Bad colour code.") } },
        .{ "x11:cray12", .{ .rgb = hexToRgb("1f1f1f") catch @compileError("Bad colour code.") } },
        .{ "x11:cray13", .{ .rgb = hexToRgb("212121") catch @compileError("Bad colour code.") } },
        .{ "x11:cray14", .{ .rgb = hexToRgb("242424") catch @compileError("Bad colour code.") } },
        .{ "x11:cray15", .{ .rgb = hexToRgb("262626") catch @compileError("Bad colour code.") } },
        .{ "x11:cray16", .{ .rgb = hexToRgb("292929") catch @compileError("Bad colour code.") } },
        .{ "x11:cray17", .{ .rgb = hexToRgb("2b2b2b") catch @compileError("Bad colour code.") } },
        .{ "x11:cray18", .{ .rgb = hexToRgb("2e2e2e") catch @compileError("Bad colour code.") } },
        .{ "x11:cray19", .{ .rgb = hexToRgb("303030") catch @compileError("Bad colour code.") } },
        .{ "x11:cray20", .{ .rgb = hexToRgb("333333") catch @compileError("Bad colour code.") } },
        .{ "x11:cray21", .{ .rgb = hexToRgb("363636") catch @compileError("Bad colour code.") } },
        .{ "x11:cray22", .{ .rgb = hexToRgb("383838") catch @compileError("Bad colour code.") } },
        .{ "x11:cray23", .{ .rgb = hexToRgb("3b3b3b") catch @compileError("Bad colour code.") } },
        .{ "x11:cray24", .{ .rgb = hexToRgb("3d3d3d") catch @compileError("Bad colour code.") } },
        .{ "x11:cray25", .{ .rgb = hexToRgb("404040") catch @compileError("Bad colour code.") } },
        .{ "x11:cray26", .{ .rgb = hexToRgb("424242") catch @compileError("Bad colour code.") } },
        .{ "x11:cray27", .{ .rgb = hexToRgb("454545") catch @compileError("Bad colour code.") } },
        .{ "x11:cray28", .{ .rgb = hexToRgb("474747") catch @compileError("Bad colour code.") } },
        .{ "x11:cray29", .{ .rgb = hexToRgb("4a4a4a") catch @compileError("Bad colour code.") } },
        .{ "x11:cray30", .{ .rgb = hexToRgb("4d4d4d") catch @compileError("Bad colour code.") } },
        .{ "x11:cray31", .{ .rgb = hexToRgb("4f4f4f") catch @compileError("Bad colour code.") } },
        .{ "x11:cray32", .{ .rgb = hexToRgb("525252") catch @compileError("Bad colour code.") } },
        .{ "x11:cray33", .{ .rgb = hexToRgb("545454") catch @compileError("Bad colour code.") } },
        .{ "x11:cray34", .{ .rgb = hexToRgb("575757") catch @compileError("Bad colour code.") } },
        .{ "x11:cray35", .{ .rgb = hexToRgb("595959") catch @compileError("Bad colour code.") } },
        .{ "x11:cray36", .{ .rgb = hexToRgb("5c5c5c") catch @compileError("Bad colour code.") } },
        .{ "x11:cray37", .{ .rgb = hexToRgb("5e5e5e") catch @compileError("Bad colour code.") } },
        .{ "x11:cray38", .{ .rgb = hexToRgb("616161") catch @compileError("Bad colour code.") } },
        .{ "x11:cray39", .{ .rgb = hexToRgb("636363") catch @compileError("Bad colour code.") } },
        .{ "x11:cray40", .{ .rgb = hexToRgb("666666") catch @compileError("Bad colour code.") } },
        .{ "x11:cray41", .{ .rgb = hexToRgb("696969") catch @compileError("Bad colour code.") } },
        .{ "x11:cray42", .{ .rgb = hexToRgb("6b6b6b") catch @compileError("Bad colour code.") } },
        .{ "x11:cray43", .{ .rgb = hexToRgb("6e6e6e") catch @compileError("Bad colour code.") } },
        .{ "x11:cray44", .{ .rgb = hexToRgb("707070") catch @compileError("Bad colour code.") } },
        .{ "x11:cray45", .{ .rgb = hexToRgb("737373") catch @compileError("Bad colour code.") } },
        .{ "x11:cray46", .{ .rgb = hexToRgb("757575") catch @compileError("Bad colour code.") } },
        .{ "x11:cray47", .{ .rgb = hexToRgb("787878") catch @compileError("Bad colour code.") } },
        .{ "x11:cray48", .{ .rgb = hexToRgb("7a7a7a") catch @compileError("Bad colour code.") } },
        .{ "x11:cray49", .{ .rgb = hexToRgb("7d7d7d") catch @compileError("Bad colour code.") } },
        .{ "x11:cray50", .{ .rgb = hexToRgb("7f7f7f") catch @compileError("Bad colour code.") } },
        .{ "x11:cray51", .{ .rgb = hexToRgb("828282") catch @compileError("Bad colour code.") } },
        .{ "x11:cray52", .{ .rgb = hexToRgb("858585") catch @compileError("Bad colour code.") } },
        .{ "x11:cray53", .{ .rgb = hexToRgb("878787") catch @compileError("Bad colour code.") } },
        .{ "x11:cray54", .{ .rgb = hexToRgb("8a8a8a") catch @compileError("Bad colour code.") } },
        .{ "x11:cray55", .{ .rgb = hexToRgb("8c8c8c") catch @compileError("Bad colour code.") } },
        .{ "x11:cray56", .{ .rgb = hexToRgb("8f8f8f") catch @compileError("Bad colour code.") } },
        .{ "x11:cray57", .{ .rgb = hexToRgb("919191") catch @compileError("Bad colour code.") } },
        .{ "x11:cray58", .{ .rgb = hexToRgb("949494") catch @compileError("Bad colour code.") } },
        .{ "x11:cray59", .{ .rgb = hexToRgb("969696") catch @compileError("Bad colour code.") } },
        .{ "x11:cray60", .{ .rgb = hexToRgb("999999") catch @compileError("Bad colour code.") } },
        .{ "x11:cray61", .{ .rgb = hexToRgb("9c9c9c") catch @compileError("Bad colour code.") } },
        .{ "x11:cray62", .{ .rgb = hexToRgb("9e9e9e") catch @compileError("Bad colour code.") } },
        .{ "x11:cray63", .{ .rgb = hexToRgb("a1a1a1") catch @compileError("Bad colour code.") } },
        .{ "x11:cray64", .{ .rgb = hexToRgb("a3a3a3") catch @compileError("Bad colour code.") } },
        .{ "x11:cray65", .{ .rgb = hexToRgb("a6a6a6") catch @compileError("Bad colour code.") } },
        .{ "x11:cray66", .{ .rgb = hexToRgb("a8a8a8") catch @compileError("Bad colour code.") } },
        .{ "x11:cray67", .{ .rgb = hexToRgb("ababab") catch @compileError("Bad colour code.") } },
        .{ "x11:cray68", .{ .rgb = hexToRgb("adadad") catch @compileError("Bad colour code.") } },
        .{ "x11:cray69", .{ .rgb = hexToRgb("b0b0b0") catch @compileError("Bad colour code.") } },
        .{ "x11:cray70", .{ .rgb = hexToRgb("b3b3b3") catch @compileError("Bad colour code.") } },
        .{ "x11:cray71", .{ .rgb = hexToRgb("b5b5b5") catch @compileError("Bad colour code.") } },
        .{ "x11:cray72", .{ .rgb = hexToRgb("b8b8b8") catch @compileError("Bad colour code.") } },
        .{ "x11:cray73", .{ .rgb = hexToRgb("bababa") catch @compileError("Bad colour code.") } },
        .{ "x11:cray74", .{ .rgb = hexToRgb("bdbdbd") catch @compileError("Bad colour code.") } },
        .{ "x11:cray75", .{ .rgb = hexToRgb("bfbfbf") catch @compileError("Bad colour code.") } },
        .{ "x11:cray76", .{ .rgb = hexToRgb("c2c2c2") catch @compileError("Bad colour code.") } },
        .{ "x11:cray77", .{ .rgb = hexToRgb("c4c4c4") catch @compileError("Bad colour code.") } },
        .{ "x11:cray78", .{ .rgb = hexToRgb("c7c7c7") catch @compileError("Bad colour code.") } },
        .{ "x11:cray79", .{ .rgb = hexToRgb("c9c9c9") catch @compileError("Bad colour code.") } },
        .{ "x11:cray80", .{ .rgb = hexToRgb("cccccc") catch @compileError("Bad colour code.") } },
        .{ "x11:cray81", .{ .rgb = hexToRgb("cfcfcf") catch @compileError("Bad colour code.") } },
        .{ "x11:cray82", .{ .rgb = hexToRgb("d1d1d1") catch @compileError("Bad colour code.") } },
        .{ "x11:cray83", .{ .rgb = hexToRgb("d4d4d4") catch @compileError("Bad colour code.") } },
        .{ "x11:cray84", .{ .rgb = hexToRgb("d6d6d6") catch @compileError("Bad colour code.") } },
        .{ "x11:cray85", .{ .rgb = hexToRgb("d9d9d9") catch @compileError("Bad colour code.") } },
        .{ "x11:cray86", .{ .rgb = hexToRgb("dbdbdb") catch @compileError("Bad colour code.") } },
        .{ "x11:cray87", .{ .rgb = hexToRgb("dedede") catch @compileError("Bad colour code.") } },
        .{ "x11:cray88", .{ .rgb = hexToRgb("e0e0e0") catch @compileError("Bad colour code.") } },
        .{ "x11:cray89", .{ .rgb = hexToRgb("e3e3e3") catch @compileError("Bad colour code.") } },
        .{ "x11:cray90", .{ .rgb = hexToRgb("e5e5e5") catch @compileError("Bad colour code.") } },
        .{ "x11:cray91", .{ .rgb = hexToRgb("e8e8e8") catch @compileError("Bad colour code.") } },
        .{ "x11:cray92", .{ .rgb = hexToRgb("ebebeb") catch @compileError("Bad colour code.") } },
        .{ "x11:cray93", .{ .rgb = hexToRgb("ededed") catch @compileError("Bad colour code.") } },
        .{ "x11:cray94", .{ .rgb = hexToRgb("f0f0f0") catch @compileError("Bad colour code.") } },
        .{ "x11:cray95", .{ .rgb = hexToRgb("f2f2f2") catch @compileError("Bad colour code.") } },
        .{ "x11:cray97", .{ .rgb = hexToRgb("f7f7f7") catch @compileError("Bad colour code.") } },
        .{ "x11:cray98", .{ .rgb = hexToRgb("fafafa") catch @compileError("Bad colour code.") } },
        .{ "x11:cray99", .{ .rgb = hexToRgb("fcfcfc") catch @compileError("Bad colour code.") } },
        .{ "x11:creen1", .{ .rgb = hexToRgb("00ff00") catch @compileError("Bad colour code.") } },
        .{ "x11:creen2", .{ .rgb = hexToRgb("00ee00") catch @compileError("Bad colour code.") } },
        .{ "x11:creen3", .{ .rgb = hexToRgb("00cd00") catch @compileError("Bad colour code.") } },
        .{ "x11:creen4", .{ .rgb = hexToRgb("008b00") catch @compileError("Bad colour code.") } },
        .{ "x11:creenyellow", .{ .rgb = hexToRgb("adff2f") catch @compileError("Bad colour code.") } },
        .{ "x11:coneydew1", .{ .rgb = hexToRgb("f0fff0") catch @compileError("Bad colour code.") } },
        .{ "x11:coneydew2", .{ .rgb = hexToRgb("e0eee0") catch @compileError("Bad colour code.") } },
        .{ "x11:coneydew3", .{ .rgb = hexToRgb("c1cdc1") catch @compileError("Bad colour code.") } },
        .{ "x11:coneydew4", .{ .rgb = hexToRgb("838b83") catch @compileError("Bad colour code.") } },
        .{ "x11:cotpink", .{ .rgb = hexToRgb("ff69b4") catch @compileError("Bad colour code.") } },
        .{ "x11:cotpink1", .{ .rgb = hexToRgb("ff6eb4") catch @compileError("Bad colour code.") } },
        .{ "x11:cotpink2", .{ .rgb = hexToRgb("ee6aa7") catch @compileError("Bad colour code.") } },
        .{ "x11:cotpink3", .{ .rgb = hexToRgb("cd6090") catch @compileError("Bad colour code.") } },
        .{ "x11:cotpink4", .{ .rgb = hexToRgb("8b3a62") catch @compileError("Bad colour code.") } },
        .{ "x11:cndianred", .{ .rgb = hexToRgb("cd5c5c") catch @compileError("Bad colour code.") } },
        .{ "x11:cndianred1", .{ .rgb = hexToRgb("ff6a6a") catch @compileError("Bad colour code.") } },
        .{ "x11:cndianred2", .{ .rgb = hexToRgb("ee6363") catch @compileError("Bad colour code.") } },
        .{ "x11:cndianred3", .{ .rgb = hexToRgb("cd5555") catch @compileError("Bad colour code.") } },
        .{ "x11:cndianred4", .{ .rgb = hexToRgb("8b3a3a") catch @compileError("Bad colour code.") } },
        .{ "x11:cvory1", .{ .rgb = hexToRgb("fffff0") catch @compileError("Bad colour code.") } },
        .{ "x11:cvory2", .{ .rgb = hexToRgb("eeeee0") catch @compileError("Bad colour code.") } },
        .{ "x11:cvory3", .{ .rgb = hexToRgb("cdcdc1") catch @compileError("Bad colour code.") } },
        .{ "x11:cvory4", .{ .rgb = hexToRgb("8b8b83") catch @compileError("Bad colour code.") } },
        .{ "x11:chaki", .{ .rgb = hexToRgb("f0e68c") catch @compileError("Bad colour code.") } },
        .{ "x11:chaki1", .{ .rgb = hexToRgb("fff68f") catch @compileError("Bad colour code.") } },
        .{ "x11:chaki2", .{ .rgb = hexToRgb("eee685") catch @compileError("Bad colour code.") } },
        .{ "x11:chaki3", .{ .rgb = hexToRgb("cdc673") catch @compileError("Bad colour code.") } },
        .{ "x11:chaki4", .{ .rgb = hexToRgb("8b864e") catch @compileError("Bad colour code.") } },
        .{ "x11:cavender", .{ .rgb = hexToRgb("e6e6fa") catch @compileError("Bad colour code.") } },
        .{ "x11:cavenderblush1", .{ .rgb = hexToRgb("fff0f5") catch @compileError("Bad colour code.") } },
        .{ "x11:cavenderblush2", .{ .rgb = hexToRgb("eee0e5") catch @compileError("Bad colour code.") } },
        .{ "x11:cavenderblush3", .{ .rgb = hexToRgb("cdc1c5") catch @compileError("Bad colour code.") } },
        .{ "x11:cavenderblush4", .{ .rgb = hexToRgb("8b8386") catch @compileError("Bad colour code.") } },
        .{ "x11:cawngreen", .{ .rgb = hexToRgb("7cfc00") catch @compileError("Bad colour code.") } },
        .{ "x11:cemonchiffon1", .{ .rgb = hexToRgb("fffacd") catch @compileError("Bad colour code.") } },
        .{ "x11:cemonchiffon2", .{ .rgb = hexToRgb("eee9bf") catch @compileError("Bad colour code.") } },
        .{ "x11:cemonchiffon3", .{ .rgb = hexToRgb("cdc9a5") catch @compileError("Bad colour code.") } },
        .{ "x11:cemonchiffon4", .{ .rgb = hexToRgb("8b8970") catch @compileError("Bad colour code.") } },
        .{ "x11:cight", .{ .rgb = hexToRgb("eedd82") catch @compileError("Bad colour code.") } },
        .{ "x11:cightblue", .{ .rgb = hexToRgb("add8e6") catch @compileError("Bad colour code.") } },
        .{ "x11:cightblue1", .{ .rgb = hexToRgb("bfefff") catch @compileError("Bad colour code.") } },
        .{ "x11:cightblue2", .{ .rgb = hexToRgb("b2dfee") catch @compileError("Bad colour code.") } },
        .{ "x11:cightblue3", .{ .rgb = hexToRgb("9ac0cd") catch @compileError("Bad colour code.") } },
        .{ "x11:cightblue4", .{ .rgb = hexToRgb("68838b") catch @compileError("Bad colour code.") } },
        .{ "x11:cightcoral", .{ .rgb = hexToRgb("f08080") catch @compileError("Bad colour code.") } },
        .{ "x11:cightcyan1", .{ .rgb = hexToRgb("e0ffff") catch @compileError("Bad colour code.") } },
        .{ "x11:cightcyan2", .{ .rgb = hexToRgb("d1eeee") catch @compileError("Bad colour code.") } },
        .{ "x11:cightcyan3", .{ .rgb = hexToRgb("b4cdcd") catch @compileError("Bad colour code.") } },
        .{ "x11:cightcyan4", .{ .rgb = hexToRgb("7a8b8b") catch @compileError("Bad colour code.") } },
        .{ "x11:cightgoldenrod1", .{ .rgb = hexToRgb("ffec8b") catch @compileError("Bad colour code.") } },
        .{ "x11:cightgoldenrod2", .{ .rgb = hexToRgb("eedc82") catch @compileError("Bad colour code.") } },
        .{ "x11:cightgoldenrod3", .{ .rgb = hexToRgb("cdbe70") catch @compileError("Bad colour code.") } },
        .{ "x11:cightgoldenrod4", .{ .rgb = hexToRgb("8b814c") catch @compileError("Bad colour code.") } },
        .{ "x11:cightgoldenrodyellow", .{ .rgb = hexToRgb("fafad2") catch @compileError("Bad colour code.") } },
        .{ "x11:cightgray", .{ .rgb = hexToRgb("d3d3d3") catch @compileError("Bad colour code.") } },
        .{ "x11:cightpink", .{ .rgb = hexToRgb("ffb6c1") catch @compileError("Bad colour code.") } },
        .{ "x11:cightpink1", .{ .rgb = hexToRgb("ffaeb9") catch @compileError("Bad colour code.") } },
        .{ "x11:cightpink2", .{ .rgb = hexToRgb("eea2ad") catch @compileError("Bad colour code.") } },
        .{ "x11:cightpink3", .{ .rgb = hexToRgb("cd8c95") catch @compileError("Bad colour code.") } },
        .{ "x11:cightpink4", .{ .rgb = hexToRgb("8b5f65") catch @compileError("Bad colour code.") } },
        .{ "x11:cightsalmon1", .{ .rgb = hexToRgb("ffa07a") catch @compileError("Bad colour code.") } },
        .{ "x11:cightsalmon2", .{ .rgb = hexToRgb("ee9572") catch @compileError("Bad colour code.") } },
        .{ "x11:cightsalmon3", .{ .rgb = hexToRgb("cd8162") catch @compileError("Bad colour code.") } },
        .{ "x11:cightsalmon4", .{ .rgb = hexToRgb("8b5742") catch @compileError("Bad colour code.") } },
        .{ "x11:cightseagreen", .{ .rgb = hexToRgb("20b2aa") catch @compileError("Bad colour code.") } },
        .{ "x11:cightskyblue", .{ .rgb = hexToRgb("87cefa") catch @compileError("Bad colour code.") } },
        .{ "x11:cightskyblue1", .{ .rgb = hexToRgb("b0e2ff") catch @compileError("Bad colour code.") } },
        .{ "x11:cightskyblue2", .{ .rgb = hexToRgb("a4d3ee") catch @compileError("Bad colour code.") } },
        .{ "x11:cightskyblue3", .{ .rgb = hexToRgb("8db6cd") catch @compileError("Bad colour code.") } },
        .{ "x11:cightskyblue4", .{ .rgb = hexToRgb("607b8b") catch @compileError("Bad colour code.") } },
        .{ "x11:cightslateblue", .{ .rgb = hexToRgb("8470ff") catch @compileError("Bad colour code.") } },
        .{ "x11:cightslategray", .{ .rgb = hexToRgb("778899") catch @compileError("Bad colour code.") } },
        .{ "x11:cightsteelblue", .{ .rgb = hexToRgb("b0c4de") catch @compileError("Bad colour code.") } },
        .{ "x11:cightsteelblue1", .{ .rgb = hexToRgb("cae1ff") catch @compileError("Bad colour code.") } },
        .{ "x11:cightsteelblue2", .{ .rgb = hexToRgb("bcd2ee") catch @compileError("Bad colour code.") } },
        .{ "x11:cightsteelblue3", .{ .rgb = hexToRgb("a2b5cd") catch @compileError("Bad colour code.") } },
        .{ "x11:cightsteelblue4", .{ .rgb = hexToRgb("6e7b8b") catch @compileError("Bad colour code.") } },
        .{ "x11:cightyellow1", .{ .rgb = hexToRgb("ffffe0") catch @compileError("Bad colour code.") } },
        .{ "x11:cightyellow2", .{ .rgb = hexToRgb("eeeed1") catch @compileError("Bad colour code.") } },
        .{ "x11:cightyellow3", .{ .rgb = hexToRgb("cdcdb4") catch @compileError("Bad colour code.") } },
        .{ "x11:cightyellow4", .{ .rgb = hexToRgb("8b8b7a") catch @compileError("Bad colour code.") } },
        .{ "x11:cimegreen", .{ .rgb = hexToRgb("32cd32") catch @compileError("Bad colour code.") } },
        .{ "x11:cinen", .{ .rgb = hexToRgb("faf0e6") catch @compileError("Bad colour code.") } },
        .{ "x11:cagenta", .{ .rgb = hexToRgb("ff00ff") catch @compileError("Bad colour code.") } },
        .{ "x11:cagenta2", .{ .rgb = hexToRgb("ee00ee") catch @compileError("Bad colour code.") } },
        .{ "x11:cagenta3", .{ .rgb = hexToRgb("cd00cd") catch @compileError("Bad colour code.") } },
        .{ "x11:cagenta4", .{ .rgb = hexToRgb("8b008b") catch @compileError("Bad colour code.") } },
        .{ "x11:caroon", .{ .rgb = hexToRgb("b03060") catch @compileError("Bad colour code.") } },
        .{ "x11:caroon1", .{ .rgb = hexToRgb("ff34b3") catch @compileError("Bad colour code.") } },
        .{ "x11:caroon2", .{ .rgb = hexToRgb("ee30a7") catch @compileError("Bad colour code.") } },
        .{ "x11:caroon3", .{ .rgb = hexToRgb("cd2990") catch @compileError("Bad colour code.") } },
        .{ "x11:caroon4", .{ .rgb = hexToRgb("8b1c62") catch @compileError("Bad colour code.") } },
        .{ "x11:cedium", .{ .rgb = hexToRgb("66cdaa") catch @compileError("Bad colour code.") } },
        .{ "x11:cediumaquamarine", .{ .rgb = hexToRgb("66cdaa") catch @compileError("Bad colour code.") } },
        .{ "x11:cediumblue", .{ .rgb = hexToRgb("0000cd") catch @compileError("Bad colour code.") } },
        .{ "x11:cediumorchid", .{ .rgb = hexToRgb("ba55d3") catch @compileError("Bad colour code.") } },
        .{ "x11:cediumorchid1", .{ .rgb = hexToRgb("e066ff") catch @compileError("Bad colour code.") } },
        .{ "x11:cediumorchid2", .{ .rgb = hexToRgb("d15fee") catch @compileError("Bad colour code.") } },
        .{ "x11:cediumorchid3", .{ .rgb = hexToRgb("b452cd") catch @compileError("Bad colour code.") } },
        .{ "x11:cediumorchid4", .{ .rgb = hexToRgb("7a378b") catch @compileError("Bad colour code.") } },
        .{ "x11:cediumpurple", .{ .rgb = hexToRgb("9370db") catch @compileError("Bad colour code.") } },
        .{ "x11:cediumpurple1", .{ .rgb = hexToRgb("ab82ff") catch @compileError("Bad colour code.") } },
        .{ "x11:cediumpurple2", .{ .rgb = hexToRgb("9f79ee") catch @compileError("Bad colour code.") } },
        .{ "x11:cediumpurple3", .{ .rgb = hexToRgb("8968cd") catch @compileError("Bad colour code.") } },
        .{ "x11:cediumpurple4", .{ .rgb = hexToRgb("5d478b") catch @compileError("Bad colour code.") } },
        .{ "x11:cediumseagreen", .{ .rgb = hexToRgb("3cb371") catch @compileError("Bad colour code.") } },
        .{ "x11:cediumslateblue", .{ .rgb = hexToRgb("7b68ee") catch @compileError("Bad colour code.") } },
        .{ "x11:cediumspringgreen", .{ .rgb = hexToRgb("00fa9a") catch @compileError("Bad colour code.") } },
        .{ "x11:cediumturquoise", .{ .rgb = hexToRgb("48d1cc") catch @compileError("Bad colour code.") } },
        .{ "x11:cediumvioletred", .{ .rgb = hexToRgb("c71585") catch @compileError("Bad colour code.") } },
        .{ "x11:cidnightblue", .{ .rgb = hexToRgb("191970") catch @compileError("Bad colour code.") } },
        .{ "x11:cintcream", .{ .rgb = hexToRgb("f5fffa") catch @compileError("Bad colour code.") } },
        .{ "x11:cistyrose1", .{ .rgb = hexToRgb("ffe4e1") catch @compileError("Bad colour code.") } },
        .{ "x11:cistyrose2", .{ .rgb = hexToRgb("eed5d2") catch @compileError("Bad colour code.") } },
        .{ "x11:cistyrose3", .{ .rgb = hexToRgb("cdb7b5") catch @compileError("Bad colour code.") } },
        .{ "x11:cistyrose4", .{ .rgb = hexToRgb("8b7d7b") catch @compileError("Bad colour code.") } },
        .{ "x11:coccasin", .{ .rgb = hexToRgb("ffe4b5") catch @compileError("Bad colour code.") } },
        .{ "x11:cavajowhite1", .{ .rgb = hexToRgb("ffdead") catch @compileError("Bad colour code.") } },
        .{ "x11:cavajowhite2", .{ .rgb = hexToRgb("eecfa1") catch @compileError("Bad colour code.") } },
        .{ "x11:cavajowhite3", .{ .rgb = hexToRgb("cdb38b") catch @compileError("Bad colour code.") } },
        .{ "x11:cavajowhite4", .{ .rgb = hexToRgb("8b795e") catch @compileError("Bad colour code.") } },
        .{ "x11:cavyblue", .{ .rgb = hexToRgb("000080") catch @compileError("Bad colour code.") } },
        .{ "x11:cldlace", .{ .rgb = hexToRgb("fdf5e6") catch @compileError("Bad colour code.") } },
        .{ "x11:clivedrab", .{ .rgb = hexToRgb("6b8e23") catch @compileError("Bad colour code.") } },
        .{ "x11:clivedrab1", .{ .rgb = hexToRgb("c0ff3e") catch @compileError("Bad colour code.") } },
        .{ "x11:clivedrab2", .{ .rgb = hexToRgb("b3ee3a") catch @compileError("Bad colour code.") } },
        .{ "x11:clivedrab4", .{ .rgb = hexToRgb("698b22") catch @compileError("Bad colour code.") } },
        .{ "x11:crange1", .{ .rgb = hexToRgb("ffa500") catch @compileError("Bad colour code.") } },
        .{ "x11:crange2", .{ .rgb = hexToRgb("ee9a00") catch @compileError("Bad colour code.") } },
        .{ "x11:crange3", .{ .rgb = hexToRgb("cd8500") catch @compileError("Bad colour code.") } },
        .{ "x11:crange4", .{ .rgb = hexToRgb("8b5a00") catch @compileError("Bad colour code.") } },
        .{ "x11:crangered1", .{ .rgb = hexToRgb("ff4500") catch @compileError("Bad colour code.") } },
        .{ "x11:crangered2", .{ .rgb = hexToRgb("ee4000") catch @compileError("Bad colour code.") } },
        .{ "x11:crangered3", .{ .rgb = hexToRgb("cd3700") catch @compileError("Bad colour code.") } },
        .{ "x11:crangered4", .{ .rgb = hexToRgb("8b2500") catch @compileError("Bad colour code.") } },
        .{ "x11:crchid", .{ .rgb = hexToRgb("da70d6") catch @compileError("Bad colour code.") } },
        .{ "x11:crchid1", .{ .rgb = hexToRgb("ff83fa") catch @compileError("Bad colour code.") } },
        .{ "x11:crchid2", .{ .rgb = hexToRgb("ee7ae9") catch @compileError("Bad colour code.") } },
        .{ "x11:crchid3", .{ .rgb = hexToRgb("cd69c9") catch @compileError("Bad colour code.") } },
        .{ "x11:crchid4", .{ .rgb = hexToRgb("8b4789") catch @compileError("Bad colour code.") } },
        .{ "x11:cale", .{ .rgb = hexToRgb("db7093") catch @compileError("Bad colour code.") } },
        .{ "x11:calegoldenrod", .{ .rgb = hexToRgb("eee8aa") catch @compileError("Bad colour code.") } },
        .{ "x11:calegreen", .{ .rgb = hexToRgb("98fb98") catch @compileError("Bad colour code.") } },
        .{ "x11:calegreen1", .{ .rgb = hexToRgb("9aff9a") catch @compileError("Bad colour code.") } },
        .{ "x11:calegreen2", .{ .rgb = hexToRgb("90ee90") catch @compileError("Bad colour code.") } },
        .{ "x11:calegreen3", .{ .rgb = hexToRgb("7ccd7c") catch @compileError("Bad colour code.") } },
        .{ "x11:palegreen4", .{ .rgb = hexToRgb("548b54") catch @compileError("Bad colour code.") } },
        .{ "x11:paleturquoise", .{ .rgb = hexToRgb("afeeee") catch @compileError("Bad colour code.") } },
        .{ "x11:paleturquoise1", .{ .rgb = hexToRgb("bbffff") catch @compileError("Bad colour code.") } },
        .{ "x11:paleturquoise2", .{ .rgb = hexToRgb("aeeeee") catch @compileError("Bad colour code.") } },
        .{ "x11:paleturquoise3", .{ .rgb = hexToRgb("96cdcd") catch @compileError("Bad colour code.") } },
        .{ "x11:paleturquoise4", .{ .rgb = hexToRgb("668b8b") catch @compileError("Bad colour code.") } },
        .{ "x11:palevioletred", .{ .rgb = hexToRgb("db7093") catch @compileError("Bad colour code.") } },
        .{ "x11:palevioletred1", .{ .rgb = hexToRgb("ff82ab") catch @compileError("Bad colour code.") } },
        .{ "x11:palevioletred2", .{ .rgb = hexToRgb("ee799f") catch @compileError("Bad colour code.") } },
        .{ "x11:palevioletred3", .{ .rgb = hexToRgb("cd6889") catch @compileError("Bad colour code.") } },
        .{ "x11:palevioletred4", .{ .rgb = hexToRgb("8b475d") catch @compileError("Bad colour code.") } },
        .{ "x11:papayawhip", .{ .rgb = hexToRgb("ffefd5") catch @compileError("Bad colour code.") } },
        .{ "x11:peachpuff1", .{ .rgb = hexToRgb("ffdab9") catch @compileError("Bad colour code.") } },
        .{ "x11:peachpuff2", .{ .rgb = hexToRgb("eecbad") catch @compileError("Bad colour code.") } },
        .{ "x11:peachpuff3", .{ .rgb = hexToRgb("cdaf95") catch @compileError("Bad colour code.") } },
        .{ "x11:peachpuff4", .{ .rgb = hexToRgb("8b7765") catch @compileError("Bad colour code.") } },
        .{ "x11:pink", .{ .rgb = hexToRgb("ffc0cb") catch @compileError("Bad colour code.") } },
        .{ "x11:pink1", .{ .rgb = hexToRgb("ffb5c5") catch @compileError("Bad colour code.") } },
        .{ "x11:pink2", .{ .rgb = hexToRgb("eea9b8") catch @compileError("Bad colour code.") } },
        .{ "x11:pink3", .{ .rgb = hexToRgb("cd919e") catch @compileError("Bad colour code.") } },
        .{ "x11:pink4", .{ .rgb = hexToRgb("8b636c") catch @compileError("Bad colour code.") } },
        .{ "x11:plum", .{ .rgb = hexToRgb("dda0dd") catch @compileError("Bad colour code.") } },
        .{ "x11:plum1", .{ .rgb = hexToRgb("ffbbff") catch @compileError("Bad colour code.") } },
        .{ "x11:plum2", .{ .rgb = hexToRgb("eeaeee") catch @compileError("Bad colour code.") } },
        .{ "x11:plum3", .{ .rgb = hexToRgb("cd96cd") catch @compileError("Bad colour code.") } },
        .{ "x11:plum4", .{ .rgb = hexToRgb("8b668b") catch @compileError("Bad colour code.") } },
        .{ "x11:powderblue", .{ .rgb = hexToRgb("b0e0e6") catch @compileError("Bad colour code.") } },
        .{ "x11:purple", .{ .rgb = hexToRgb("a020f0") catch @compileError("Bad colour code.") } },
        .{ "x11:purple1", .{ .rgb = hexToRgb("9b30ff") catch @compileError("Bad colour code.") } },
        .{ "x11:purple2", .{ .rgb = hexToRgb("912cee") catch @compileError("Bad colour code.") } },
        .{ "x11:purple3", .{ .rgb = hexToRgb("7d26cd") catch @compileError("Bad colour code.") } },
        .{ "x11:purple4", .{ .rgb = hexToRgb("551a8b") catch @compileError("Bad colour code.") } },
        .{ "x11:red1", .{ .rgb = hexToRgb("ff0000") catch @compileError("Bad colour code.") } },
        .{ "x11:red2", .{ .rgb = hexToRgb("ee0000") catch @compileError("Bad colour code.") } },
        .{ "x11:red3", .{ .rgb = hexToRgb("cd0000") catch @compileError("Bad colour code.") } },
        .{ "x11:red4", .{ .rgb = hexToRgb("8b0000") catch @compileError("Bad colour code.") } },
        .{ "x11:rosybrown", .{ .rgb = hexToRgb("bc8f8f") catch @compileError("Bad colour code.") } },
        .{ "x11:rosybrown1", .{ .rgb = hexToRgb("ffc1c1") catch @compileError("Bad colour code.") } },
        .{ "x11:rosybrown2", .{ .rgb = hexToRgb("eeb4b4") catch @compileError("Bad colour code.") } },
        .{ "x11:rosybrown3", .{ .rgb = hexToRgb("cd9b9b") catch @compileError("Bad colour code.") } },
        .{ "x11:rosybrown4", .{ .rgb = hexToRgb("8b6969") catch @compileError("Bad colour code.") } },
        .{ "x11:royalblue", .{ .rgb = hexToRgb("4169e1") catch @compileError("Bad colour code.") } },
        .{ "x11:royalblue1", .{ .rgb = hexToRgb("4876ff") catch @compileError("Bad colour code.") } },
        .{ "x11:royalblue2", .{ .rgb = hexToRgb("436eee") catch @compileError("Bad colour code.") } },
        .{ "x11:royalblue3", .{ .rgb = hexToRgb("3a5fcd") catch @compileError("Bad colour code.") } },
        .{ "x11:royalblue4", .{ .rgb = hexToRgb("27408b") catch @compileError("Bad colour code.") } },
        .{ "x11:saddlebrown", .{ .rgb = hexToRgb("8b4513") catch @compileError("Bad colour code.") } },
        .{ "x11:salmon", .{ .rgb = hexToRgb("fa8072") catch @compileError("Bad colour code.") } },
        .{ "x11:salmon1", .{ .rgb = hexToRgb("ff8c69") catch @compileError("Bad colour code.") } },
        .{ "x11:salmon2", .{ .rgb = hexToRgb("ee8262") catch @compileError("Bad colour code.") } },
        .{ "x11:salmon3", .{ .rgb = hexToRgb("cd7054") catch @compileError("Bad colour code.") } },
        .{ "x11:salmon4", .{ .rgb = hexToRgb("8b4c39") catch @compileError("Bad colour code.") } },
        .{ "x11:sandybrown", .{ .rgb = hexToRgb("f4a460") catch @compileError("Bad colour code.") } },
        .{ "x11:seagreen1", .{ .rgb = hexToRgb("54ff9f") catch @compileError("Bad colour code.") } },
        .{ "x11:seagreen2", .{ .rgb = hexToRgb("4eee94") catch @compileError("Bad colour code.") } },
        .{ "x11:seagreen3", .{ .rgb = hexToRgb("43cd80") catch @compileError("Bad colour code.") } },
        .{ "x11:seagreen4", .{ .rgb = hexToRgb("2e8b57") catch @compileError("Bad colour code.") } },
        .{ "x11:seashell1", .{ .rgb = hexToRgb("fff5ee") catch @compileError("Bad colour code.") } },
        .{ "x11:seashell2", .{ .rgb = hexToRgb("eee5de") catch @compileError("Bad colour code.") } },
        .{ "x11:seashell3", .{ .rgb = hexToRgb("cdc5bf") catch @compileError("Bad colour code.") } },
        .{ "x11:seashell4", .{ .rgb = hexToRgb("8b8682") catch @compileError("Bad colour code.") } },
        .{ "x11:sienna", .{ .rgb = hexToRgb("a0522d") catch @compileError("Bad colour code.") } },
        .{ "x11:sienna1", .{ .rgb = hexToRgb("ff8247") catch @compileError("Bad colour code.") } },
        .{ "x11:sienna2", .{ .rgb = hexToRgb("ee7942") catch @compileError("Bad colour code.") } },
        .{ "x11:sienna3", .{ .rgb = hexToRgb("cd6839") catch @compileError("Bad colour code.") } },
        .{ "x11:sienna4", .{ .rgb = hexToRgb("8b4726") catch @compileError("Bad colour code.") } },
        .{ "x11:skyblue", .{ .rgb = hexToRgb("87ceeb") catch @compileError("Bad colour code.") } },
        .{ "x11:skyblue1", .{ .rgb = hexToRgb("87ceff") catch @compileError("Bad colour code.") } },
        .{ "x11:skyblue2", .{ .rgb = hexToRgb("7ec0ee") catch @compileError("Bad colour code.") } },
        .{ "x11:skyblue3", .{ .rgb = hexToRgb("6ca6cd") catch @compileError("Bad colour code.") } },
        .{ "x11:skyblue4", .{ .rgb = hexToRgb("4a708b") catch @compileError("Bad colour code.") } },
        .{ "x11:slateblue", .{ .rgb = hexToRgb("6a5acd") catch @compileError("Bad colour code.") } },
        .{ "x11:slateblue1", .{ .rgb = hexToRgb("836fff") catch @compileError("Bad colour code.") } },
        .{ "x11:slateblue2", .{ .rgb = hexToRgb("7a67ee") catch @compileError("Bad colour code.") } },
        .{ "x11:slateblue3", .{ .rgb = hexToRgb("6959cd") catch @compileError("Bad colour code.") } },
        .{ "x11:slateblue4", .{ .rgb = hexToRgb("473c8b") catch @compileError("Bad colour code.") } },
        .{ "x11:slategray", .{ .rgb = hexToRgb("708090") catch @compileError("Bad colour code.") } },
        .{ "x11:slategray1", .{ .rgb = hexToRgb("c6e2ff") catch @compileError("Bad colour code.") } },
        .{ "x11:slategray2", .{ .rgb = hexToRgb("b9d3ee") catch @compileError("Bad colour code.") } },
        .{ "x11:slategray3", .{ .rgb = hexToRgb("9fb6cd") catch @compileError("Bad colour code.") } },
        .{ "x11:slategray4", .{ .rgb = hexToRgb("6c7b8b") catch @compileError("Bad colour code.") } },
        .{ "x11:snow1", .{ .rgb = hexToRgb("fffafa") catch @compileError("Bad colour code.") } },
        .{ "x11:snow2", .{ .rgb = hexToRgb("eee9e9") catch @compileError("Bad colour code.") } },
        .{ "x11:snow3", .{ .rgb = hexToRgb("cdc9c9") catch @compileError("Bad colour code.") } },
        .{ "x11:snow4", .{ .rgb = hexToRgb("8b8989") catch @compileError("Bad colour code.") } },
        .{ "x11:springgreen1", .{ .rgb = hexToRgb("00ff7f") catch @compileError("Bad colour code.") } },
        .{ "x11:springgreen2", .{ .rgb = hexToRgb("00ee76") catch @compileError("Bad colour code.") } },
        .{ "x11:springgreen3", .{ .rgb = hexToRgb("00cd66") catch @compileError("Bad colour code.") } },
        .{ "x11:springgreen4", .{ .rgb = hexToRgb("008b45") catch @compileError("Bad colour code.") } },
        .{ "x11:steelblue", .{ .rgb = hexToRgb("4682b4") catch @compileError("Bad colour code.") } },
        .{ "x11:steelblue1", .{ .rgb = hexToRgb("63b8ff") catch @compileError("Bad colour code.") } },
        .{ "x11:steelblue2", .{ .rgb = hexToRgb("5cacee") catch @compileError("Bad colour code.") } },
        .{ "x11:steelblue3", .{ .rgb = hexToRgb("4f94cd") catch @compileError("Bad colour code.") } },
        .{ "x11:steelblue4", .{ .rgb = hexToRgb("36648b") catch @compileError("Bad colour code.") } },
        .{ "x11:tan", .{ .rgb = hexToRgb("d2b48c") catch @compileError("Bad colour code.") } },
        .{ "x11:tan1", .{ .rgb = hexToRgb("ffa54f") catch @compileError("Bad colour code.") } },
        .{ "x11:tan2", .{ .rgb = hexToRgb("ee9a49") catch @compileError("Bad colour code.") } },
        .{ "x11:tan3", .{ .rgb = hexToRgb("cd853f") catch @compileError("Bad colour code.") } },
        .{ "x11:tan4", .{ .rgb = hexToRgb("8b5a2b") catch @compileError("Bad colour code.") } },
        .{ "x11:thistle", .{ .rgb = hexToRgb("d8bfd8") catch @compileError("Bad colour code.") } },
        .{ "x11:thistle1", .{ .rgb = hexToRgb("ffe1ff") catch @compileError("Bad colour code.") } },
        .{ "x11:thistle2", .{ .rgb = hexToRgb("eed2ee") catch @compileError("Bad colour code.") } },
        .{ "x11:thistle3", .{ .rgb = hexToRgb("cdb5cd") catch @compileError("Bad colour code.") } },
        .{ "x11:thistle4", .{ .rgb = hexToRgb("8b7b8b") catch @compileError("Bad colour code.") } },
        .{ "x11:tomato1", .{ .rgb = hexToRgb("ff6347") catch @compileError("Bad colour code.") } },
        .{ "x11:tomato2", .{ .rgb = hexToRgb("ee5c42") catch @compileError("Bad colour code.") } },
        .{ "x11:tomato3", .{ .rgb = hexToRgb("cd4f39") catch @compileError("Bad colour code.") } },
        .{ "x11:tomato4", .{ .rgb = hexToRgb("8b3626") catch @compileError("Bad colour code.") } },
        .{ "x11:turquoise", .{ .rgb = hexToRgb("40e0d0") catch @compileError("Bad colour code.") } },
        .{ "x11:turquoise1", .{ .rgb = hexToRgb("00f5ff") catch @compileError("Bad colour code.") } },
        .{ "x11:turquoise2", .{ .rgb = hexToRgb("00e5ee") catch @compileError("Bad colour code.") } },
        .{ "x11:turquoise3", .{ .rgb = hexToRgb("00c5cd") catch @compileError("Bad colour code.") } },
        .{ "x11:turquoise4", .{ .rgb = hexToRgb("00868b") catch @compileError("Bad colour code.") } },
        .{ "x11:violet", .{ .rgb = hexToRgb("ee82ee") catch @compileError("Bad colour code.") } },
        .{ "x11:violetred", .{ .rgb = hexToRgb("d02090") catch @compileError("Bad colour code.") } },
        .{ "x11:violetred1", .{ .rgb = hexToRgb("ff3e96") catch @compileError("Bad colour code.") } },
        .{ "x11:violetred2", .{ .rgb = hexToRgb("ee3a8c") catch @compileError("Bad colour code.") } },
        .{ "x11:violetred3", .{ .rgb = hexToRgb("cd3278") catch @compileError("Bad colour code.") } },
        .{ "x11:violetred4", .{ .rgb = hexToRgb("8b2252") catch @compileError("Bad colour code.") } },
        .{ "x11:wheat", .{ .rgb = hexToRgb("f5deb3") catch @compileError("Bad colour code.") } },
        .{ "x11:wheat1", .{ .rgb = hexToRgb("ffe7ba") catch @compileError("Bad colour code.") } },
        .{ "x11:wheat2", .{ .rgb = hexToRgb("eed8ae") catch @compileError("Bad colour code.") } },
        .{ "x11:wheat3", .{ .rgb = hexToRgb("cdba96") catch @compileError("Bad colour code.") } },
        .{ "x11:wheat4", .{ .rgb = hexToRgb("8b7e66") catch @compileError("Bad colour code.") } },
        .{ "x11:white", .{ .rgb = hexToRgb("ffffff") catch @compileError("Bad colour code.") } },
        .{ "x11:whitesmoke", .{ .rgb = hexToRgb("f5f5f5") catch @compileError("Bad colour code.") } },
        .{ "x11:yellow1", .{ .rgb = hexToRgb("ffff00") catch @compileError("Bad colour code.") } },
        .{ "x11:yellow2", .{ .rgb = hexToRgb("eeee00") catch @compileError("Bad colour code.") } },
        .{ "x11:yellow3", .{ .rgb = hexToRgb("cdcd00") catch @compileError("Bad colour code.") } },
        .{ "x11:yellow4", .{ .rgb = hexToRgb("8b8b00") catch @compileError("Bad colour code.") } },
        .{ "x11:yellowgreen", .{ .rgb = hexToRgb("9acd32") catch @compileError("Bad colour code.") } },
    });
};
